export const socSidebarLinks = [
  { href: '/', label: 'Home' },
  { href: '/about', label: 'About SOC' },
  { href: '/roadmap', label: 'Roadmap' },
  { href: '/day-wise', label: 'Day Wise Learning' },
  { href: '/logs', label: 'Linux Log Analysis' },
  { href: '/commands', label: 'Command Training' },
  { href: '/investigation', label: 'Attack Investigation' },
  { href: '/siem', label: 'SIEM Basics' },
  { href: '/threat-hunting', label: 'Threat Hunting' },
  { href: '/incident-response', label: 'Incident Response' },
  { href: '/labs', label: 'Labs' },
  { href: '/resources', label: 'Resources' },
  { href: '/student-dashboard', label: 'Student Dashboard' },
  { href: '/admin', label: 'Admin Panel' },
  { href: '/search', label: 'Search' },
];

export const homeStats = [
  { label: 'SOC Fundamentals', value: 'Beginner friendly' },
  { label: 'Practical Labs', value: 'Real logs + commands' },
  { label: 'Learning Track', value: 'Day 1 to Day 7' },
  { label: 'Focus', value: 'Blue team workflow' },
];

export const roadmapStages = [
  {
    title: 'Beginner',
    summary: 'Learn what SOC means, how logs work, and how analysts think.',
    items: ['SOC basics', 'Linux log files', 'Simple commands', 'Attack patterns'],
  },
  {
    title: 'Intermediate',
    summary: 'Connect evidence, investigate suspicious activity, and write findings.',
    items: ['SIEM basics', 'Threat hunting basics', 'Attack investigation', 'Incident response flow'],
  },
  {
    title: 'Advanced',
    summary: 'Practice deeper analysis, cross-log correlation, and response mindset.',
    items: ['DFIR concepts', 'Correlation', 'Behavior analysis', 'Case reporting'],
  },
];

export const dayPlans = [
  {
    day: 'Day 1',
    title: 'Introduction to SOC',
    notes: [
      'What a SOC is and why it matters',
      'SOC team roles and responsibilities',
      'Understanding logs and evidence',
      'Linux log files and basic analysis',
      'Common attack patterns and SIEM basics',
      'Threat hunting and incident response basics',
    ],
    commands: ['grep -i "failed" auth.log', 'last -a', 'journalctl -xe', 'ps aux | grep ssh'],
    labs: ['Failed login review', 'Suspicious root access check'],
    quiz: 'Identify which log file helps explain who logged in, who failed, and what happened before the alert.',
    practice: 'Read one auth.log sample and write a short analyst note in simple words.',
    summary: 'Day 1 builds the SOC mindset: observe, compare, and explain what the evidence says.',
  },
  {
    day: 'Day 2',
    title: 'Linux Log Investigation',
    notes: ['auth.log', 'syslog', 'wtmp', 'btmp', 'apache access and error logs'],
    commands: ['tail -f auth.log', 'less syslog', 'lastb', 'grep -R "error" /var/log/apache2/'],
    labs: ['Apache attack review', 'Brute force trace'],
    quiz: 'Which log shows failed login attempts on Linux?',
    practice: 'Find three suspicious lines and explain why they look important.',
    summary: 'You learn where Linux stores useful traces and how to move through them quickly.',
  },
  {
    day: 'Day 3',
    title: 'Command Practice',
    notes: ['grep', 'tail', 'cat', 'less', 'last', 'lastb', 'ps aux', 'netstat', 'journalctl'],
    commands: ['grep -n "Failed" auth.log', 'ps aux | head', 'netstat -tulpn', 'journalctl --since today'],
    labs: ['Command drill', 'Live investigation practice'],
    quiz: 'Which command is best for filtering one word from a huge log file?',
    practice: 'Use three commands to answer one SOC question from a log sample.',
    summary: 'The goal is speed with discipline: choose the right command for the right clue.',
  },
  {
    day: 'Day 4',
    title: 'Suspicious Activity Detection',
    notes: ['Failed login spikes', 'Root login traces', 'Odd process names', 'Unusual ports'],
    commands: ['grep -Ei "fail|invalid" auth.log', 'ps aux | grep -v grep', 'netstat -anp'],
    labs: ['Suspicious login detection', 'Malware process check'],
    quiz: 'What clue often shows a brute force attempt before success?',
    practice: 'Write a short finding that separates noise from suspicious behavior.',
    summary: 'You start grouping clues into patterns that matter to analysts.',
  },
  {
    day: 'Day 5',
    title: 'SIEM Basics',
    notes: ['Log centralization', 'Alerts', 'Correlation', 'Dashboards', 'Splunk, ELK, Wazuh, QRadar'],
    commands: ['search failed_login', 'stats count by host', 'table time, user, action'],
    labs: ['Build a simple alert view', 'Find the noisy event source'],
    quiz: 'Why does a SIEM help a SOC analyst?',
    practice: 'Turn one log pattern into a simple alert idea.',
    summary: 'SIEM is where many logs become one investigation view.',
  },
  {
    day: 'Day 6',
    title: 'Threat Hunting Basics',
    notes: ['Search for hidden activity', 'Look for behavior, not only alerts', 'Create a hypothesis', 'Check logs and endpoint traces'],
    commands: ['grep -R "cron" /var/log', 'journalctl | grep -i suspicious', 'netstat -tulpn'],
    labs: ['Hidden attacker search', 'Unusual behavior drill'],
    quiz: 'What is the main difference between hunting and alert response?',
    practice: 'Write one hunting question in plain English.',
    summary: 'Threat hunting is a deliberate search for what security tools may miss.',
  },
  {
    day: 'Day 7',
    title: 'Incident Response Basics',
    notes: ['Detection', 'Analysis', 'Containment', 'Eradication', 'Recovery', 'Reporting'],
    commands: ['grep -i incident case.log', 'journalctl -p err', 'last -a'],
    labs: ['Basic IR flow', 'Final case write-up'],
    quiz: 'What is the first goal after confirming a real incident?',
    practice: 'Write a short response summary using simple analyst language.',
    summary: 'You close the loop by showing how analysts respond, recover, and report.',
  },
];

export const logSections = [
  {
    name: 'auth.log',
    stores: 'Login attempts, sudo use, SSH activity, authentication messages',
    why: 'It is the first place to check when login behavior looks strange.',
    attacks: ['Failed SSH brute force', 'Suspicious root login', 'Invalid user attempts'],
    useCases: ['Track who logged in', 'See repeated failures', 'Spot privilege use'],
  },
  {
    name: 'syslog',
    stores: 'System services, general system events, service errors',
    why: 'It helps explain what the machine was doing when something went wrong.',
    attacks: ['Service crash before attack', 'Unexpected service changes'],
    useCases: ['Check service health', 'Confirm error timing', 'Correlate with auth.log'],
  },
  {
    name: 'apache access logs',
    stores: 'Every web request, IP address, URL, status code, user agent',
    why: 'It shows who visited the web server and which requests failed or looked odd.',
    attacks: ['Path scanning', 'Web attack payloads', 'Suspicious POST requests'],
    useCases: ['See request patterns', 'Detect probing', 'Match IPs with other logs'],
  },
  {
    name: 'apache error logs',
    stores: 'Server errors, broken requests, application issues',
    why: 'It gives context when a web attack or bad request causes an error.',
    attacks: ['Invalid file access', 'Exploit attempts', 'Malformed input'],
    useCases: ['Understand failed requests', 'Look for exploit clues', 'Compare with access logs'],
  },
  {
    name: 'wtmp',
    stores: 'Successful login history and session records',
    why: 'It helps confirm who logged in and when the session happened.',
    attacks: ['Unexpected successful login', 'Odd time-of-day access'],
    useCases: ['Review login timeline', 'Confirm user session', 'Validate analyst findings'],
  },
  {
    name: 'btmp',
    stores: 'Failed login attempts',
    why: 'It is useful for spotting brute force activity and repeated failures.',
    attacks: ['Password guessing', 'Targeted login abuse'],
    useCases: ['Count failures', 'Find source IPs', 'Measure attack pressure'],
  },
];

export const commandLessons = [
  {
    name: 'grep',
    syntax: 'grep "pattern" file',
    explanation: 'Searches for matching text inside a file.',
    usage: 'Filter login failures, usernames, IPs, or error keywords.',
    example: 'grep -i "failed" auth.log',
    mistakes: ['Forgetting -i when case is different', 'Searching the wrong file'],
    output: 'Lines containing the word failed',
    exercises: ['Find all failed logins', 'Search for root references'],
  },
  {
    name: 'tail',
    syntax: 'tail -f file',
    explanation: 'Shows the end of a file and can follow new lines live.',
    usage: 'Watch active logs while an event is happening.',
    example: 'tail -f /var/log/auth.log',
    mistakes: ['Using it on the wrong log', 'Missing -f for live follow'],
    output: 'Latest lines in the log',
    exercises: ['Watch a login event live', 'Track new Apache errors'],
  },
  {
    name: 'cat',
    syntax: 'cat file',
    explanation: 'Prints the whole file to the screen.',
    usage: 'Quickly view a small sample file or combine with pipes.',
    example: 'cat sample.log | grep -i ssh',
    mistakes: ['Using cat on huge logs without filters'],
    output: 'Full file text',
    exercises: ['Print a sample log', 'Pipe the output into grep'],
  },
  {
    name: 'less',
    syntax: 'less file',
    explanation: 'Opens a file for safe scrolling and searching.',
    usage: 'Best for large logs when you need to move through them carefully.',
    example: 'less /var/log/syslog',
    mistakes: ['Forgetting you can search inside less', 'Using cat on large files instead'],
    output: 'Interactive file viewer',
    exercises: ['Search inside a log file', 'Jump to a suspicious line'],
  },
  {
    name: 'last',
    syntax: 'last',
    explanation: 'Shows recent successful logins and sessions.',
    usage: 'Check which users logged in and when.',
    example: 'last -a',
    mistakes: ['Using it for failed logins', 'Ignoring unusual login times'],
    output: 'Login history list',
    exercises: ['Find the latest login', 'Spot unusual hours'],
  },
  {
    name: 'lastb',
    syntax: 'lastb',
    explanation: 'Shows failed login attempts.',
    usage: 'Useful for brute force review and password attack clues.',
    example: 'sudo lastb',
    mistakes: ['Forgetting sudo', 'Ignoring repeated source IPs'],
    output: 'Failed login history list',
    exercises: ['Count repeated failures', 'Find one suspicious source'],
  },
  {
    name: 'ps aux',
    syntax: 'ps aux',
    explanation: 'Lists running processes with useful details.',
    usage: 'Check for suspicious programs, odd names, or unauthorized tools.',
    example: 'ps aux | grep ssh',
    mistakes: ['Not comparing process names carefully', 'Missing hidden malicious-looking names'],
    output: 'Process list',
    exercises: ['Find an SSH process', 'Spot an odd process name'],
  },
  {
    name: 'netstat',
    syntax: 'netstat -tulpn',
    explanation: 'Shows listening ports and network connections.',
    usage: 'Useful for seeing odd services or unexpected outbound links.',
    example: 'netstat -tulpn',
    mistakes: ['Forgetting root access for process names', 'Ignoring unexpected ports'],
    output: 'Open ports and connections',
    exercises: ['Find listening services', 'Check for strange outbound connections'],
  },
  {
    name: 'journalctl',
    syntax: 'journalctl --since today',
    explanation: 'Reads systemd logs and service messages.',
    usage: 'Check service failures, kernel events, and recent system changes.',
    example: 'journalctl -p err --since today',
    mistakes: ['Not limiting by time', 'Ignoring error priority filters'],
    output: 'Structured system logs',
    exercises: ['Search today’s errors', 'Track one service failure'],
  },
];

export const investigations = [
  {
    title: 'SSH Brute Force Attack',
    scenario: 'A server is getting many failed SSH login attempts from the same IP.',
    logs: ['auth.log shows repeated invalid users', 'btmp shows failed sessions'],
    steps: ['Count failures', 'Check source IP', 'Look for one success after many failures', 'Write the finding'],
    commands: ['grep -i "failed" auth.log', 'lastb', 'grep -i "accepted" auth.log'],
    findings: ['Many failed attempts', 'One successful login after the spike'],
    summary: 'This looks like a brute force attack followed by a successful guess or reused password.',
  },
  {
    title: 'Suspicious Root Login',
    scenario: 'A root login appears at a strange time from a new location.',
    logs: ['auth.log contains root entry', 'wtmp confirms login time'],
    steps: ['Confirm the time', 'Check whether root access is expected', 'Look for other admin activity', 'Document risk'],
    commands: ['last -a', 'grep -i "root" auth.log', 'journalctl --since today'],
    findings: ['Login time does not match normal admin work', 'Root activity needs review'],
    summary: 'A root login outside the normal pattern must be treated as high priority.',
  },
  {
    title: 'Malware Process Detection',
    scenario: 'A process with a strange name is using CPU and network in a suspicious way.',
    logs: ['ps aux output', 'journalctl service errors', 'netstat connections'],
    steps: ['List running processes', 'Check the process owner', 'Inspect open connections', 'Look for persistence clues'],
    commands: ['ps aux', 'netstat -tulpn', 'journalctl -xe'],
    findings: ['Odd process name', 'Unexpected network behavior'],
    summary: 'The analyst should verify whether the process is legitimate or part of malware activity.',
  },
  {
    title: 'Suspicious Network Connection',
    scenario: 'A host connects to an unusual external IP after login.',
    logs: ['netstat shows outbound link', 'auth.log shows recent access'],
    steps: ['Find the source process', 'Check login timing', 'Match to user activity', 'Write down the behavior'],
    commands: ['netstat -anp', 'ps aux', 'grep -i "accepted" auth.log'],
    findings: ['Unknown remote connection', 'Possible unauthorized tool or beacon'],
    summary: 'The goal is to understand whether the connection is normal or a sign of compromise.',
  },
  {
    title: 'Apache Attack Investigation',
    scenario: 'Web logs show strange request paths and repeated errors.',
    logs: ['Apache access log', 'Apache error log'],
    steps: ['Find repeated requests', 'Check status codes', 'Look for attack patterns', 'Document the attacker behavior'],
    commands: ['grep "404" access.log', 'grep -i "error" error.log', 'grep -i "../" access.log'],
    findings: ['Path scanning and suspicious request patterns'],
    summary: 'Web attacks often leave clear traces in access and error logs.',
  },
];

export const siemBasics = [
  'Centralize logs from many systems into one place',
  'Create alerts when suspicious patterns happen',
  'Correlate different events to build a story',
  'Use dashboards to see what needs attention first',
  'Common SIEM tools include Splunk, ELK Stack, Wazuh, and QRadar',
];

export const threatHuntingBasics = [
  'Search for hidden attackers even when no alert has fired',
  'Start with a hypothesis, not random guessing',
  'Look at behavior across logs, processes, and connections',
  'Use clues like odd timing, unusual commands, or repeated failures',
  'Write down what you checked and what you ruled out',
];

export const incidentResponsePhases = [
  { name: 'Detection', detail: 'Notice that something looks wrong.' },
  { name: 'Analysis', detail: 'Confirm the issue and understand the scope.' },
  { name: 'Containment', detail: 'Limit damage and stop spread.' },
  { name: 'Eradication', detail: 'Remove the cause or attacker presence.' },
  { name: 'Recovery', detail: 'Restore systems and verify normal operation.' },
  { name: 'Reporting', detail: 'Write the case summary and lessons learned.' },
];

export const labs = [
  {
    title: 'Failed SSH Login Analysis',
    objective: 'Learn how to read failed login traces and understand brute force behavior.',
    scenario: 'A Linux server shows repeated failed SSH attempts.',
    logs: ['auth.log', 'btmp'],
    commands: ['grep -i "failed" auth.log', 'lastb', 'grep -i "invalid" auth.log'],
    process: ['Find the source IP', 'Count failures', 'Check for one success after failures'],
    expected: ['Repeated failed attempts', 'Suspicious source'],
    answer: 'The log pattern matches brute force login abuse.',
  },
  {
    title: 'Brute Force Detection',
    objective: 'Spot a password guessing attack from Linux evidence.',
    scenario: 'Many users receive login failures from one IP.',
    logs: ['auth.log', 'btmp'],
    commands: ['grep -i "failure" auth.log', 'lastb', 'grep -i "accepted" auth.log'],
    process: ['Compare usernames', 'Look for bursts', 'Write the final suspicion'],
    expected: ['High failure count', 'Possible brute force'],
    answer: 'The system is under brute force pressure.',
  },
  {
    title: 'Suspicious Login Detection',
    objective: 'Identify odd successful logins that need review.',
    scenario: 'A normal account logs in at an unusual time.',
    logs: ['auth.log', 'wtmp'],
    commands: ['last -a', 'grep -i "accepted" auth.log'],
    process: ['Check time', 'Check user history', 'Compare with normal behavior'],
    expected: ['Login outside normal hours', 'Needs analyst follow-up'],
    answer: 'The login is suspicious because it does not fit the user’s normal pattern.',
  },
  {
    title: 'Apache Log Investigation',
    objective: 'Find web attack clues in access and error logs.',
    scenario: 'A web server shows repeated 404s and strange paths.',
    logs: ['apache access log', 'apache error log'],
    commands: ['grep "404" access.log', 'grep -i "error" error.log'],
    process: ['Look for attack paths', 'Check status codes', 'Summarize what happened'],
    expected: ['Path scanning', 'Suspicious request patterns'],
    answer: 'The web activity looks like attack probing or exploitation attempts.',
  },
  {
    title: 'Basic Malware Investigation',
    objective: 'Use process and connection clues to spot suspicious activity.',
    scenario: 'One process has a strange name and unusual network use.',
    logs: ['ps aux', 'netstat -tulpn', 'journalctl'],
    commands: ['ps aux', 'netstat -anp', 'journalctl -xe'],
    process: ['Identify the process owner', 'Check the connection', 'Write a plain language finding'],
    expected: ['Odd process', 'Unexpected connection'],
    answer: 'The process may be malicious or unauthorized.',
  },
  {
    title: 'Basic Incident Response Lab',
    objective: 'Practice the full response flow from detection to reporting.',
    scenario: 'An attacker may have logged in and used SSH repeatedly.',
    logs: ['auth.log', 'btmp', 'wtmp'],
    commands: ['grep -i "failed" auth.log', 'lastb', 'last -a'],
    process: ['Detect', 'Analyze', 'Contain', 'Report'],
    expected: ['Clear attack timeline', 'Actionable next step'],
    answer: 'The evidence supports a response case with follow-up containment.',
  },
];

export const resources = [
  { name: 'PDF Notes', detail: 'Download topic-wise notes for revision.' },
  { name: 'Command Cheat Sheets', detail: 'Quick references for the most used Linux commands.' },
  { name: 'Linux Resources', detail: 'Beginner Linux reading for SOC students.' },
  { name: 'SOC Learning Links', detail: 'Curated blue team learning pages and labs.' },
  { name: 'Practice Datasets', detail: 'Sample logs for log analysis and investigations.' },
];
